#!/bin/bash

echo "🚀 InventoryPro - Деплой на ams.it-uae.com"
echo "=========================================="
echo ""
echo "Этот скрипт поможет вам:"
echo "1. Загрузить код в GitHub"
echo "2. Развернуть на сервере"
echo "3. Настроить Expo"
echo ""
echo "Детальные инструкции в файлах:"
echo "  - COMPLETE_DEPLOYMENT.md (полная инструкция)"
echo "  - GITHUB_SETUP.md (настройка GitHub)"
echo "  - SERVER_DEPLOY.md (деплой на сервер)"
echo "  - EXPO_SETUP.md (настройка Expo)"
echo ""
echo "Быстрый старт:"
echo ""
echo "1. GitHub:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git remote add origin https://github.com/rakhatu/inventorypro.git"
echo "   git push -u origin main"
echo ""
echo "2. Сервер:"
echo "   ssh root@ams.it-uae.com"
echo "   cd /var/www && git clone https://github.com/rakhatu/inventorypro.git"
echo "   cd inventorypro"
echo "   Создать .env файл с POSTGRES_PASSWORD и SECRET_KEY"
echo "   docker-compose -f docker-compose.prod.yml up -d --build"
echo ""
echo "3. Expo:"
echo "   cd mobile"
echo "   eas login"
echo "   eas build --platform android --profile preview"
echo ""

